\" This appears at the top.
.TH "Foo" "3" "Bar" "Baz" "Qux"
.SH NAME
foobar \- custom function decorations
.\" --------------------------------------------------------------------------
.SH SYNOPSIS
.nf
.B #include <decorations.h>
.PP
.BI "void foobar(void);"
.fi
.\" --------------------------------------------------------------------------
.SH DESCRIPTION
Function added to verify its man page is documented with a custom preamble and epilogue.
\" This appears at the bottom.