.TH "MY PROJECT" "3"
.SH NAME
links.h \- TEST URLS and LINKS
.SH SYNOPSIS
.nf
.B #include <links.h>
.fi
.SH DESCRIPTION
Go review the documentation for the \f[B]nop\f[R](3) function.
.PP
Then go browse code on
.UR https://github.com
GitHub
.UE
or another source hosting website.
.PP
For short code snipets, use
.UR https://gist.github.com/
Gist
.UE .
.PP
If you like Canonical there is always
.UR https://launchpad.net/
Canonical Lanchpad
.UE !!!
.TS
tab(;);
l l.
\fBFunctions\fR;\fBDescription\fR
_
\fBnop\fR(3);T{
Do nothing.
T}
.TE
.SH SEE ALSO
.BR nop (3)