.TH "MY PROJECT" "3"
.SH NAME
links.h \- TEST URLS and LINKS
.\" --------------------------------------------------------------------------
.SH SYNOPSIS
.nf
.B #include <links.h>
.fi
.\" --------------------------------------------------------------------------
.SH DESCRIPTION
Go review the documentation for the \f[B]nop\f[R](3) function.
.PP
Then go browse code on
.UR https://github.com
GitHub
.UE
or another source hosting website.
.\" -------------------------------------
.SS Functions
.TP
.BR nop (3)
Do nothing.
.\" --------------------------------------------------------------------------
.SH SEE ALSO
.BR nop (3)
