.TH "MY PROJECT" "3"
.SH NAME
nop \- do nothing
.SH SYNOPSIS
.nf
.B #include <links.h>
.PP
.BI "void nop(void);"
.fi
.SH DESCRIPTION
And if you don't like GitHub, there's always
.UR https://bitbucket.org/
BitBucket
.UE ,
.UR https://codeberg.org/
Codeberg
.UE ,
and
.UR https://en.wikipedia.org/wiki/GitLab
GitLab
.UE !