.TH "JUDO" "3"
.SH NAME
judo_number \- floating-point storage type
.SH LIBRARY
Embeddable JSON parser (libjudo, -ljudo)
.SH SYNOPSIS
.nf
.B #include <judo.h>
.PP
.BI "typedef long double judo_number;"
.fi
.SH DESCRIPTION
This can be defined as a \f[C]float\f[R], \f[C]double\f[R], or \f[C]long double\f[R] at configuration time.