.TH "JUDO" "3"
.SH NAME
judo.h \- embeddable JSON Parser
.SH LIBRARY
Embeddable JSON parser (libjudo, -ljudo)
.SH SYNOPSIS
.nf
.B #include <judo.h>
.fi
.SH DESCRIPTION
Embeddable JSON Parser.
.SS Scanner
The Judo scanner processes JSON source text into semantic elements.
\f[B]judo_element\f[R](3) are notable marker points within the JSON stream that may or may not correspond with a JSON token.
You can find semantic elements with the #judo_scan function, which returns them one-at-a-time.
This function is intended to be called repeatedly until all semantic elements have been processed or an error halts the scanner.
.TS
tab(;);
l l.
\fBDefines\fR;\fBDescription\fR
_
\fBJUDO_MAXDEPTH\fR(3);T{
Maximum nesting depth.
T}
\fBJUDO_ERRMAX\fR(3);T{
Maximum length of an error.
T}

.T&
l l.
\fBEnumerations\fR;\fBDescription\fR
_
\fBjudo_element\fR(3);T{
Semantic element.
T}
.TE