.TH "MY PROJECT" "3"
.SH NAME
admonition.h \- admonition testing
.SH SYNOPSIS
.nf
.B #include <admonition.h>
.fi
.SH DESCRIPTION
Whereas it is essential to promote the development of friendly relations between nations.
.PP
Whereas the peoples of the United Nations have in the Charter reaffirmed their faith in fundamental human rights.
In the dignity and worth of the human person.
In the equal rights of men and women and have determined to promote social progress and better standards of life in larger freedom.
.PP
In co-operation with the United Nations.