.TH "MY PROJECT" "3"
.SH NAME
code-references.h \- code examples
.SH SYNOPSIS
.nf
.B #include <code-references.h>
.fi
.SH DESCRIPTION
Recognition of the inherent dignity and of the equal and inalienable rights of all members of the human family.
The foundation of freedom, justice and peace in the world.
Disregard and contempt for human rights have resulted in barbarous acts which have outraged the conscience of mankind.
The advent of a world in which human beings shall enjoy freedom from fear and want has been proclaimed as the highest aspiration of the common people.
.PP
.in +4n
.EX
// https://google.com
int main(void) {
    struct Foo foo = {0};
    foobar(&foo);
    return 0;
}
.EE
.in
.PP
Whereas it is essential to promote the development of friendly relations between nations.
.PP
This is a code blurb that referenes \f[V]Foo\f[R] and \f[V]foobar\f[R] which should NOT be linked.
.TS
tab(;);
l l.
\fBFunctions\fR;\fBDescription\fR
_
\fBfoobar\fR(3);T{
This is a function.
T}
.TE