.TH "MY PROJECT" "3"
.SH NAME
foobar \- this is a function
.SH SYNOPSIS
.nf
.B #include <code-references.h>
.PP
.BI "void foobar(const struct Foo *" foo ");"
.fi
.SH DESCRIPTION
The following is a code example that references \f[B]Foo\f[R](3) and \f[B]foobar\f[R](3).
This is a code blurb that referenes \f[C]Foo\f[R] and \f[C]foobar\f[R] which should NOT be linked.
.PP
.in +4n
.EX
void DoThing(void) {
    const struct Foo f = {0};
    foobar(&f);
}
.EE
.in
.SH SEE ALSO
.BR Foo (3)