.TH "MY PROJECT" "3"
.SH NAME
chkerr \- check for errors
.\" --------------------------------------------------------------------------
.SH SYNOPSIS
.nf
.B #include <functions.h>
.PP
.BI "int chkerr(void);"
.fi
.\" --------------------------------------------------------------------------
.SH DESCRIPTION
Checks for an error by its code.
.\" --------------------------------------------------------------------------
.SH RETURN VALUE
.TP
OK
no error occured.
.TP
NOMEM
Out of memory error occured.
.TP
NOPERM, NOACCESS, NOWRITE
Missing permissions error
