.TH "MY PROJECT" "3"
.SH NAME
println \- print some formatted text
.SH SYNOPSIS
.nf
.B #include <functions.h>
.PP
.BI "int println(char *" buf ", const char *" fmt ", ...);"
.fi
.SH DESCRIPTION
Formats \f[I]fmt\f[R] using the same format escape characters as \f[V]printf\f[R] and then writes the result to \f[I]buf\f[R].
.SH PARAMETERS
.TP
buf
Buffer the formatted string will be written to.
.TP
fmt
Format of the resulting string, using printf format specifiers.
.SH RETURN VALUE
The number of characters written to \f[I]buf\f[R] or \f[V]-1\f[R] if an error occured.