.TH "MY PROJECT" "3"
.SH NAME
unsupported.h \- unsupported tags
.SH SYNOPSIS
.nf
.B #include <unsupported.h>
.fi
.SH DESCRIPTION
This text is anchored using the Doxygen command of the same name.
.PP
.RS
.IP \[bu] 2
\f[C]AlignLeft\f[R] left alignment.
.IP \[bu] 2
\f[C]AlignCenter\f[R] center alignment.
.IP \[bu] 2
\f[C]AlignRight\f[R] right alignment
.RE
The word text should be in italics.
.PP
This sentence should contain a  emoji.
.PP
The following is an image:
.PP
The following is a LaTeX formula  embedded within a paragraph.
.PP
The end.