.TH "MY PROJECT" "3"
.SH NAME
deprecated.h \- no darn good, very bad header file
.SH SYNOPSIS
.nf
.B #include <deprecated.h>
.fi
.SH DESCRIPTION
This header file has its own DEPRECATED section.
.TS
tab(;);
l l.
\fBFunctions\fR;\fBDescription\fR
_
\fBfoo\fR(3);T{
An old deprecated function.
T}
\fBbar\fR(3);T{
The new hotness.
T}
.TE
.SH DEPRECATION
Do not use this header file anymore.