.TH "MY PROJECT" "3"
.SH NAME
deprecated.h \- no darn good, very bad header file
.\" --------------------------------------------------------------------------
.SH SYNOPSIS
.nf
.B #include <deprecated.h>
.fi
.\" --------------------------------------------------------------------------
.SH DESCRIPTION
This header file has its own DEPRECATED section.
.\" -------------------------------------
.SS Functions
.TP
.BR foo (3)
An old deprecated function.
.TP
.BR bar (3)
The new hotness.
.\" --------------------------------------------------------------------------
.SH DEPRECATION
Do not use this header file anymore.
.\" --------------------------------------------------------------------------
.SH SEE ALSO
.BR foo (3),
.BR bar (3)
