.TH "MY PROJECT" "3"
.SH NAME
foo \- an old deprecated function
.SH SYNOPSIS
.nf
.B #include <deprecated.h>
.PP
.BI "void foo(void);"
.fi
.SH DESCRIPTION
This function has its own DEPRECATED section.
.SH DEPRECATION
This function will be removed in the next major release of the library.
Use \f[B]bar\f[R](3) instead.
.SH SEE ALSO
.BR bar (3)