.TH "MY PROJECT" "3"
.SH NAME
bar \- performs bar actons
.\" --------------------------------------------------------------------------
.SH SYNOPSIS
.nf
.B #include <functions_grouped.h>
.PP
.BI "void bar(void);"
.fi
.\" --------------------------------------------------------------------------
.SH DESCRIPTION
Does bar things.
.\" --------------------------------------------------------------------------
.SH SEE ALSO
.BR foo (3),
.BR baz (3)
