.TH "MY PROJECT" "3"
.SH NAME
fred \- finds fred
.\" --------------------------------------------------------------------------
.SH SYNOPSIS
.nf
.B #include <functions_grouped.h>
.PP
.BI "void fred(void);"
.fi
.\" --------------------------------------------------------------------------
.SH DESCRIPTION
Discover the location of Fred.
.\" --------------------------------------------------------------------------
.SH SEE ALSO
.BR waldo (3)
