.TH "MY PROJECT" "3"
.SH NAME
functions_grouped.h \- defines grouped functions
.\" --------------------------------------------------------------------------
.SH SYNOPSIS
.nf
.B #include <functions_grouped.h>
.fi
.\" --------------------------------------------------------------------------
.SH DESCRIPTION
This header file defines functions belonging to various groups and subgroups.
The purpose of this test case is to verify that functions in the same group are always added to each functions SEE ALSO man page section.
.\" -------------------------------------
.SS Functions
.TP
.BR foo (3)
Performs foo actons.
.TP
.BR bar (3)
Performs bar actons.
.TP
.BR baz (3)
Performs baz actons.
.TP
.BR qux (3)
Performs qux actons.
.TP
.BR waldo (3)
Finds waldo.
.TP
.BR fred (3)
Finds fred.
.\" --------------------------------------------------------------------------
.SH SEE ALSO
.BR foo (3),
.BR bar (3),
.BR baz (3),
.BR qux (3),
.BR waldo (3),
.BR fred (3)
