.TH "MY PROJECT" "3"
.SH NAME
waldo \- finds waldo
.\" --------------------------------------------------------------------------
.SH SYNOPSIS
.nf
.B #include <functions_grouped.h>
.PP
.BI "void waldo(void);"
.fi
.\" --------------------------------------------------------------------------
.SH DESCRIPTION
Discover the location of Waldo.
.\" --------------------------------------------------------------------------
.SH SEE ALSO
.BR fred (3)
