.TH "MY PROJECT" "3"
.SH NAME
INVALID_KEY \- this preproccessor macro evaluates to a constant
.SH SYNOPSIS
.nf
.B #include <preprocessor.h>
.PP
.B #define INVALID_KEY "InvalidKey"
.fi
.SH DESCRIPTION
You can treat this macro like a variable if you want.
This macro accepts no arguments, but the \f[B]ADD\f[R](3) macro does.
.SH SEE ALSO
.BR ADD (3)