.TH "MY PROJECT" "3"
.SH NAME
bar \- cast to a Foo
.\" --------------------------------------------------------------------------
.SH SYNOPSIS
.nf
.B #include <functions/functions.h>
.PP
.BI "const Foo bar(const double **const " very_long_argument_name_to_force_wrapping ");"
.fi
.\" --------------------------------------------------------------------------
.SH DESCRIPTION
Reinterpret \f[I]qux\f[R] into a Foo object.
.\" --------------------------------------------------------------------------
.SH RETURN VALUE
Informational object.
