.TH "MY PROJECT" "3"
.SH NAME
foo \- cast to a frob
.\" --------------------------------------------------------------------------
.SH SYNOPSIS
.nf
.B #include <functions/functions.h>
.PP
.BI "const void *foo(const void *" bar ");"
.fi
.\" --------------------------------------------------------------------------
.SH DESCRIPTION
Reinterpret \f[I]bar\f[R] into a frob object.
.\" --------------------------------------------------------------------------
.SH RETURN VALUE
The casting of the input object to another.
