.TH "MY PROJECT" "3"
.SH NAME
functions.h \- various function signatures
.\" --------------------------------------------------------------------------
.SH SYNOPSIS
.nf
.B #include <functions/functions.h>
.fi
.\" --------------------------------------------------------------------------
.SH DESCRIPTION
This file attempts to test against various function signatures.
.\" -------------------------------------
.SS Functions
.TP
.BR nop (3)
Does nothing.
.TP
.BR nop2 (3)
Does nothing but accepts arguments.
.TP
.BR foo (3)
Cast to a frob.
.TP
.BR bar (3)
Cast to a Foo.
.TP
.BR baz (3)
Do the thing.
.TP
.BR println (3)
Print some formatted text.
.TP
.BR chkerr (3)
Check for errors.
.\" --------------------------------------------------------------------------
.SH SEE ALSO
.BR nop (3),
.BR nop2 (3),
.BR foo (3),
.BR bar (3),
.BR baz (3),
.BR println (3),
.BR chkerr (3)
