.TH "MY PROJECT" "3"
.SH NAME
nop2 \- does nothing but accepts arguments
.\" --------------------------------------------------------------------------
.SH SYNOPSIS
.nf
.B #include <functions/functions.h>
.PP
.BI "void nop2();"
.fi
.\" --------------------------------------------------------------------------
.SH DESCRIPTION
Test whether empty function signatures format correctly.
