.TH "MY PROJECT" "3"
.SH NAME
println \- print some formatted text
.SH SYNOPSIS
.nf
.B #include <functions/functions.h>
.PP
.BI "int println(char *" buf ", const char *" fmt ", ...);"
.fi
.SH DESCRIPTION
Formats \f[I]fmt\f[R] using the same format escape characters as \f[B]printf\f[R](3) and then writes the result to \f[I]buf\f[R].
.SH RETURN VALUE
The number of characters written to \f[I]buf\f[R] or \f[C]-1\f[R] if an error occured.