.TH "FROB" "3"
.SH NAME
doodad.h \- create and manipulate doodad objects
.\" --------------------------------------------------------------------------
.SH LIBRARY
Create and manipulate Frobs (libfrob, -lfrob)
.\" --------------------------------------------------------------------------
.SH SYNOPSIS
.nf
.B #include <doodad.h>
.fi
.\" --------------------------------------------------------------------------
.SH DESCRIPTION
Doodads are little gizmos of nothingness.
They don't do much by themselves but when combined with a \f[I]Frob\f[R] they form the building blocks of something much more complex.
.\" -------------------------------------
.SS The Doodad structure
Represents a Doodad object.
.PP
.in +4n
.EX
struct Doodad {
    int gizmo;
    int gadget;
};
.EE
.in
.PP
This is presented as an opaque pointer.
.PP
.\" -------------------------------------
.SS The Result enumeration
Possible Doodad assembly results.
.PP
.in +4n
.EX
enum Result {
    RESULT_OK,
    RESULT_HALF,
    RESULT_FAIL,
};
.EE
.in
.PP
.\" -------------------------------------
.SS The DoodadFlags type
Bitflag type.
.PP
.in +4n
.EX
typedef int DoodadFlags;
.EE
.in
.PP
.\" -------------------------------------
.SS The Doodad type
Represents a Doodad object.
.PP
.in +4n
.EX
typedef struct Doodad Doodad;
.EE
.in
.PP
This is presented as an opaque pointer.
.PP
.\" -------------------------------------
.SS The DoodadFlagDefault variable
The default Doodad configuration.
.PP
.in +4n
.EX
const int DoodadFlagDefault;
.EE
.in
.PP
.\" -------------------------------------
.SS The DoodadFlagAssembled variable
Flag indicating the Doodad should come preassembled.
.PP
.in +4n
.EX
const int DoodadFlagAssembled;
.EE
.in
.PP
.\" -------------------------------------
.SS Functions
.TP
.BR doodad_new (3)
Construct a Doodad object.
.TP
.BR doodad_free (3)
Free a Doodad object.
.TP
.BR doodad_assemble (3)
Assemble a Doodad object.
.\" --------------------------------------------------------------------------
.SH SEE ALSO
.BR doodad_new (3),
.BR doodad_free (3),
.BR doodad_assemble (3)
