.TH "FROB" "3"
.SH NAME
doodad_free \- free a Doodad object
.\" --------------------------------------------------------------------------
.SH LIBRARY
Create and manipulate Frobs (libfrob, -lfrob)
.\" --------------------------------------------------------------------------
.SH SYNOPSIS
.nf
.B #include <doodad.h>
.PP
.BI "void doodad_free(Doodad *" doodad ");"
.fi
.\" --------------------------------------------------------------------------
.SH DESCRIPTION
Release all resources associated with the \f[I]struct Doodad\f[R] object.
.\" --------------------------------------------------------------------------
.SH SEE ALSO
.BR doodad_new (3),
.BR doodad_assemble (3)
