.TH "FROB" "3"
.SH NAME
doodad_new \- construct a Doodad object
.\" --------------------------------------------------------------------------
.SH LIBRARY
Create and manipulate Frobs (libfrob, -lfrob)
.\" --------------------------------------------------------------------------
.SH SYNOPSIS
.nf
.B #include <doodad.h>
.PP
.BI "Doodad *doodad_new(DoodadFlags " flags ");"
.fi
.\" --------------------------------------------------------------------------
.SH DESCRIPTION
Create a \f[I]struct Doodad\f[R] object with options.
You must release the \f[I]struct Doodad\f[R] object to prevent resource leakage by calling \f[B]doodad_free\f[R](3).
.\" --------------------------------------------------------------------------
.SH RETURN VALUE
Instance of a \f[I]struct Doodad\f[R] object or \f[V]NULL\f[R] on allocation failure.
.\" --------------------------------------------------------------------------
.SH SEE ALSO
.BR doodad_free (3),
.BR doodad_assemble (3)
