.TH "FROBLE" "3"
.SH NAME
DoodadFlagAssembled \- flag indicating the Doodad should come preassembled
.SH LIBRARY
Create and manipulate Frobs (libfrob, -lfrob)
.SH SYNOPSIS
.nf
.B #include <doodad.h>
.PP
.B const int DoodadFlagAssembled;
.fi
.SH DESCRIPTION
Flag indicating the Doodad should come preassembled.