.TH "FROBLE" "3"
.SH NAME
doodad_free \- free a Doodad object
.SH LIBRARY
Create and manipulate Frobs (libfrob, -lfrob)
.SH SYNOPSIS
.nf
.B #include <dood.h>
.PP
.BI "void doodad_free(Doodad *" doodad ");"
.fi
.SH DESCRIPTION
Release all resources associated with the \f[B]Doodad\f[R](3) object.
.SH SEE ALSO
.BR Doodad (3)