.TH "FROBLE" "3"
.SH NAME
doodad_new \- construct a Doodad object
.SH LIBRARY
Create and manipulate Frobs (libfrob, -lfrob)
.SH SYNOPSIS
.nf
.B #include <dood.h>
.PP
.BI "Doodad *doodad_new(DoodadFlags " flags ");"
.fi
.SH DESCRIPTION
Create a \f[B]Doodad\f[R](3) object with options.
You must release the \f[B]Doodad\f[R](3) object to prevent resource leakage by calling \f[B]doodad_free\f[R](3).
.SH RETURN VALUE
Instance of a \f[B]Doodad\f[R](3) object or \f[C]NULL\f[R] on allocation failure.
.SH SEE ALSO
.BR Doodad (3),
.BR doodad_free (3),
.BR DoodadFlags (3)