.TH "FROBLE" "3"
.SH NAME
frob_free \- free a Frob object
.SH LIBRARY
Create and manipulate Frobs (libfrob, -lfrob)
.SH SYNOPSIS
.nf
.B #include <froble.h>
.PP
.BI "void frob_free(Frob *" frob ");"
.fi
.SH DESCRIPTION
Release all resources associated with the \f[B]Frob\f[R](3) object.
.SH SEE ALSO
.BR Frob (3)