.TH "FROB" "3"
.SH NAME
frob_set_doodad \- associate a doodad with a frob
.\" --------------------------------------------------------------------------
.SH LIBRARY
Create and manipulate Frobs (libfrob, -lfrob)
.\" --------------------------------------------------------------------------
.SH SYNOPSIS
.nf
.B #include <frob.h>
.PP
.BI "void frob_set_doodad(Frob *" frob ", Doodad *" doodad ");"
.fi
.\" --------------------------------------------------------------------------
.SH SEE ALSO
.BR frob_new (3),
.BR frob_free (3)
