.TH "MY PROJECT" "3"
.SH NAME
example.h \- examples section
.SH SYNOPSIS
.nf
.B #include <example.h>
.fi
.SH DESCRIPTION
This header file has an EXAMPLES section in this man page.
It also defines functions which themselves have an EXAMPLES section.
.TS
tab(;);
l l.
\fBFunctions\fR;\fBDescription\fR
_
\fBFrobnicate\fR(3);T{
Frobnicate a foo.
T}
.TE