.TH "MY PROJECT" "3"
.SH NAME
Frobnicate \- frobnicate a foo
.SH SYNOPSIS
.nf
.B #include <example.h>
.PP
.BI "void Frobnicate(int " xyz "[64]);"
.fi
.SH DESCRIPTION
This function frobnicates a foo and produces a bar.
.SH EXAMPLES
This is an example found in foo.c source file.
.PP
It's a very cool example and you will learn a lot from it!
.PP
.in +4n
.EX
#include <stdio.h>
int main(int argc, char *argv[]) {
    puts("The quick brown fox jumps over the lazy dog.");
    return 0;
}
.EE
.in