.TH "MY PROJECT" "3"
.SH NAME
Foo
.SH SYNOPSIS
.nf
.B #include <None>
.PP
.B "union Foo {"
.B "    int ***waldo[];"
.B "    const union Foo::Qux qux;"
.B "    struct Foo bar;"
.B "    int ***waldo[];"
.B "    const union Foo::Qux qux;"
.B "    struct Foo bar;"
.B "};"
.fi
.SH DESCRIPTION
This union has substructres which define fields on their parent union.
This union is better than the \f[B]Frob\f[R](3) one.
.SH FIELDS
.TP
.BR waldo
Waldo field docs.
.TP
.BR qux
.TP
.BR bar
Bar field docs.
.TP
.BR waldo
Waldo field docs.
.TP
.BR qux
.TP
.BR bar
Bar field docs.
.SH SEE ALSO
.BR Frob (3)