.TH "MY PROJECT" "3"
.SH NAME
Person
.SH SYNOPSIS
.nf
.B #include <unions.h>
.PP
.B union Person {
.RS
.B int age;
.B union Height height;
.B char fullname_delimited_by_spaces[64];
.RE
.B };
.fi
.SH FIELDS
.TP
.BR age
How many years old the person is.
.TP
.BR height
The persons height.
.TP
.BR fullname_delimited_by_spaces
This is the persons first, middle, and last name delimited by spaces.
The name of this field is intentionally long so it forces paragraph wrapping.