.TH "MY PROJECT" "3"
.SH NAME
Person
.SH SYNOPSIS
.nf
.B #include <None>
.PP
union Person {
    int age;
    union Height height;
    char fullname_delimited_by_spaces[64];
    int age;
    union Height height;
    char fullname_delimited_by_spaces[64];
};
.fi
.SH FIELDS
.TP
.BR age
How many years old the person is.
.TP
.BR height
The persons height.
.TP
.BR fullname_delimited_by_spaces
This is the persons first, middle, and last name delimited by spaces.
The name of this field is intentionally long so it forces paragraph wrapping.
.TP
.BR age
How many years old the person is.
.TP
.BR height
The persons height.
.TP
.BR fullname_delimited_by_spaces
This is the persons first, middle, and last name delimited by spaces.
The name of this field is intentionally long so it forces paragraph wrapping.