.TH "MY PROJECT" "3"
.SH NAME
escapes.h
.SH SYNOPSIS
.nf
.B #include <escapes.h>
.fi
.SH DESCRIPTION
\[char46]This line begins with a dot which might confuse man into thinking it's amacro.
.PP
\[char39]This line begins with a single quote which might confuse man into thinking it's a line continuation.
.PP
"This line begins with a double quote which might confuse man into thinking it's a comment.
.PP
\This line begins with a backslash which might confuse man into thinking it's an escape character.