.TH "MY PROJECT" "3"
.SH NAME
expect_eq \- check two integers, floating-point numbers, or pointers to determine if \f[I]X\f[R] == \f[I]Y\f[R]
.SH SYNOPSIS
.nf
.B #include <subgroups.h>
.PP
.BI "void expect_eq(int " X ", int " Y ", ...);"
.fi
.SH DESCRIPTION
If \f[I]X\f[R] != \f[I]Y\f[R], the test case fails.