.TH "MY PROJECT" "3"
.SH NAME
foo.h \- this header defines the full API for the library
.SH SYNOPSIS
.nf
.B #include <foo.h>
.fi
.SH DESCRIPTION
The main header file for the library.
.SS Assertions
Assertions are statements that check whether a particular condition holds true during the execution of tests.
.TS
tab(;);
l l.
\fBFunctions\fR;\fBDescription\fR
_
\fBquit\fR(3);T{
Quit a test case.
T}
.TE