.TH "MY PROJECT" "3"
.SH NAME
unicode.h \- various Unicode characters
.SH SYNOPSIS
.nf
.B #include <unicode.h>
.fi
.SH DESCRIPTION
This file attempts to test against various Unicode characters.
.PP
The following text is wrapped in curly "double quotation marks" and they should be replace with non-curly "double quotation mark" characters.
.PP
The following text is wrapped in curly 'single quotation marks' and they should be replace with non-curly 'single quotation mark' characters.