.TH "MY PROJECT" "3"
.SH NAME
foobar \- this is an awesome function
.SH SYNOPSIS
.nf
.B #include <extra-sections.h>
.PP
.BI "void foobar(void);"
.fi
.SH DESCRIPTION
This function has its own AUTHORS and BUGS section.
.SH BUGS
Not all memory is freed by the implementation.
.SH AUTHORS
Jake Roe
.PP
Jane Doe