.TH "MY PROJECT" "3"
.SH NAME
ADD \- sum two numbers and return the result
.SH SYNOPSIS
.nf
.B #include <preprocessor.h>
.PP
.BI "#define ADD(" X ", " Y ");"
.fi
.SH DESCRIPTION
This is a type-generic macro for performing addition between two numeric types.
The left-side is given as \f[I]X\f[R] and the right-side is given as \f[I]Y\f[R] and the result of adding them is returned.