.TH "MY PROJECT" "3"
.SH NAME
ENABLE_AWESOME_FEATURE \- this preproccessor definition is defined when the super awsome feature is enabled
.SH SYNOPSIS
.nf
.B #include <preprocessor.h>
.PP
.B #define ENABLE_AWESOME_FEATURE
.fi
.SH DESCRIPTION
If you don't want the super awesome feature then delete or comment this macro.