.TH "FROBLE" "3"
.SH NAME
Doodad
.SH LIBRARY
Create and manipulate Frobs (libfrob, -lfrob)
.SH SYNOPSIS
.nf
.B #include <None>
.PP
.B "struct Doodad {"
.B "    int gizmo;"
.B "    int gadget;"
.B "    int gizmo;"
.B "    int gadget;"
.B "};"
.fi
.SH DESCRIPTION
This is presented as an opaque pointer.