.TH "FROBLE" "3"
.SH NAME
frob_set_doodad \- associate a doodad with a frob
.SH LIBRARY
Create and manipulate Frobs (libfrob, -lfrob)
.SH SYNOPSIS
.nf
.B #include <froble.h>
.PP
.BI "void frob_set_doodad(Frob *" frob ", Doodad *" doodad ");"
.fi
.SH DESCRIPTION
Associate a doodad with a frob.
.SH SEE ALSO
.BR Doodad (3),
.BR Frob (3)