.TH "FROB" "3"
.SH NAME
frob_free \- free a Frob object
.\" --------------------------------------------------------------------------
.SH LIBRARY
Create and manipulate Frobs (libfrob, -lfrob)
.\" --------------------------------------------------------------------------
.SH SYNOPSIS
.nf
.B #include <frob.h>
.PP
.BI "void frob_free(Frob *" frob ");"
.fi
.\" --------------------------------------------------------------------------
.SH DESCRIPTION
Release all resources associated with the \f[I]Frob\f[R] object.
.\" --------------------------------------------------------------------------
.SH SEE ALSO
.BR frob_new (3),
.BR frob_set_doodad (3)
