.TH "MY PROJECT" "3"
.SH NAME
structs.h \- record tests
.SH SYNOPSIS
.nf
.B #include <structs.h>
.fi
.SH DESCRIPTION
In computer science, a record (also called a structure, struct, or compound data) is a basic data structure.
Records in a database or spreadsheet are usually called "rows".
.PP
A record is a collection of fields, possibly of different data types, typically in a fixed number and sequence.
The fields of a record may also be called members, particularly in object-oriented programming; fields may also be called elements, though this risks confusion with the elements of a collection.
.PP
For example, a date could be stored as a record containing a numeric year field, a month field represented as a string, and a numeric day-of-month field.
A personnel record might contain a name, a salary, and a rank.
A Circle record might contain a center and a radius—in this instance, the center itself might be represented as a point record containing x and y coordinates.