.TH "MY PROJECT" "3"
.SH NAME
Frob
.SH SYNOPSIS
.nf
.B #include <None>
.PP
union Frob {
    const void *nop;
    const void *nop;
};
.fi
.SH DESCRIPTION
This union has one field.
It doesn't do much otherwise.
It is generally recommended to prefer the \f[B]Foo\f[R](3) union as it's more modern.
.SH SEE ALSO
.BR Foo (3)