.TH "MY PROJECT" "3"
.SH NAME
unions.h \- union type tests
.SH SYNOPSIS
.nf
.B #include <unions.h>
.fi
.SH DESCRIPTION
In computer science, a union is a value that may have any of several representations or formats within the same position in memory; that consists of a variable that may hold such a data structure.
Some programming languages support special data types, called union types, to describe such values and variables.
In other words, a union type definition will specify which of a number of permitted primitive types may be stored in its instances, e.g., "float or long integer".
In contrast with a record (or structure), which could be defined to contain both a float and an integer; in a union, there is only one value at any given time.