.TH "MY PROJECT" "3"
.SH NAME
_filter.h \- this is a filtered file
.\" --------------------------------------------------------------------------
.SH SYNOPSIS
.nf
.B #include <_filter.h>
.fi
.\" --------------------------------------------------------------------------
.SH DESCRIPTION
The slow red dog climbs over the excitable cat.
