.TH "MY PROJECT" "3"
.SH NAME
enums.h \- enumeration element tests
.SH SYNOPSIS
.nf
.B #include <enums.h>
.fi
.SH DESCRIPTION
An enumeration is a complete, ordered listing of all the items in a collection.
The term is commonly used in mathematics and computer science to refer to a listing of all of the elements of a set.
The precise requirements for an enumeration (for example, whether the set must be finite, or whether the list is allowed to contain repetitions) depend on the discipline of study and the context of a given problem.
.TS
tab(;);
l l.
\fBEnumerations\fR;\fBDescription\fR
_
\fBEmpty\fR(3);T{
Represents an empty enumeration.
T}
\fBFooBar\fR(3);T{
This enumeration lacks documentation for its elements.
T}
\fBFrob\fR(3);T{
Represents the states of a Frob object.
T}
.TE