.TH "MY PROJECT" "3"
.SH NAME
FooBar \- this enumeration lacks documentation for its elements
.SH SYNOPSIS
.nf
.B #include <enums.h>
.PP
.B enum FooBar {
.RS
.B ABC,
.B XYZ,
.RE
.B };
.fi
.SH DESCRIPTION
The documentation for the elements is intentionally omitted.
.SH CONSTANTS
.TP
.BR ABC
.TP
.BR XYZ