.TH "MY PROJECT" "3"
.SH NAME
Frob \- represents the states of a Frob object
.SH SYNOPSIS
.nf
.B #include <enums.h>
.PP
enum Frob {
    FOO,
    BAR,
    BAZ,
};
.fi
.SH DESCRIPTION
Represents various error and success states of a Frobnicator object instance.
Consult the documentation for for more details.
The default state of \f[B]Frob\f[R](3) is \f[I]FOO\f[R] so see its documentation for more details.
.SH CONSTANTS
.TP
.BR FOO
This is a \f[I]FOO\f[R] and it will never be a \f[I]BAR\f[R].
.TP
.BR BAR
This is a \f[I]BAR\f[R] and it will never ever be a \f[I]FOO\f[R].
.TP
.BR BAZ
This is a \f[I]BAZ\f[R].
It is the best constant belonging to \f[B]Frob\f[R](3) according to myself.