.TH "MY PROJECT" "3"
.SH NAME
Frob \- represents the states of a Frob object
.SH SYNOPSIS
.nf
.B #include <enums.h>
.PP
.B "enum Frob {"
.B "    FOO,"
.B "    BAR,"
.B "    BAZ,"
.B "};"
.fi
.SH DESCRIPTION
Represents various error and success states of a Frobnicator object instance.
Consult the documentation for for more details.
The default state of \f[B]Frob\f[R](3) is \f[B]FOO\f[R] so see its documentation for more details.
.SH CONSTANTS
.TP
.BR FOO
This is a \f[B]FOO\f[R] and it will never be a \f[B]BAR\f[R].
.TP
.BR BAR
This is a \f[B]BAR\f[R] and it will never ever be a \f[B]FOO\f[R].
.TP
.BR BAZ
This is a \f[B]BAZ\f[R].
It is the best constant belonging to \f[B]Frob\f[R](3) according to myself.