.TH "MY PROJECT" "3"
.SH NAME
div \- divide two numbers and return the result
.\" --------------------------------------------------------------------------
.SH SYNOPSIS
.nf
.B #include <styling.h>
.PP
.BI "double div(double " x ", double " y ");"
.fi
.\" --------------------------------------------------------------------------
.SH DESCRIPTION
Calculates the \f[I]\f[B]quotient\f[R]\f[R] of \f[I]x\f[R] and \f[I]y\f[R].
.\" --------------------------------------------------------------------------
.SH RETURN VALUE
.TP
Quotient
of \f[I]x\f[R] and \f[I]y\f[R].
.TP
NAN
if \f[I]y\f[R] is zero.
