.TH "MY PROJECT" "3"
.SH NAME
mul \- multiply two numbers and return the result
.\" --------------------------------------------------------------------------
.SH SYNOPSIS
.nf
.B #include <styling.h>
.PP
.BI "double mul(double " x ", double " y ");"
.fi
.\" --------------------------------------------------------------------------
.SH DESCRIPTION
Calculates the product of \f[I]x\f[R] and \f[I]y\f[R].
.\" --------------------------------------------------------------------------
.SH RETURN VALUE
Sum of \f[I]x\f[R] and \f[I]y\f[R].
