.TH "MY PROJECT" "3"
.SH NAME
styling.h \- lorem Ipsum
.\" --------------------------------------------------------------------------
.SH SYNOPSIS
.nf
.B #include <styling.h>
.fi
.\" --------------------------------------------------------------------------
.SH DESCRIPTION
Recognition of the inherent \f[B]dignity\f[R] and of the equal and inalienable rights of all members of the human family.
The foundation of freedom, justice and peace in the world.
Disregard and contempt for human rights have resulted in barbarous acts which have outraged the conscience of mankind.
The advent of a world in which human beings shall enjoy freedom from fear and want has been proclaimed as the \f[I]highest\f[R] aspiration of the \f[I]common\f[R] people.
.PP
Whereas it is \f[B]essential\f[R], if man is not to be compelled to have recourse, as a last resort.
\f[I]Rebellion\f[R] against tyranny and oppression, that human rights should be protected by the rule of law.
.PP
Whereas it is \f[I]essential\f[R] to \f[B]promote\f[R] the development of \f[I]friendly\f[R] relations between nations.
.\" -------------------------------------
.SS Functions
.TP
.BR mul (3)
Multiply two numbers and return the result.
.TP
.BR div (3)
Divide two numbers and return the result.
.\" --------------------------------------------------------------------------
.SH SEE ALSO
.BR mul (3),
.BR div (3)
