\" This appears at the top.
.TH "MY PROJECT" "3"
.SH NAME
preamble.h \- custom header
.\" --------------------------------------------------------------------------
.SH SYNOPSIS
.nf
.B #include <preamble.h>
.fi
.\" --------------------------------------------------------------------------
.SH DESCRIPTION
The man page for this header file should have a custom header.
