.TH "MY PROJECT" "3"
.SH NAME
variables.h \- variable tests
.SH SYNOPSIS
.nf
.B #include <variables.h>
.fi
.SH DESCRIPTION
In computer programming, a variable is an abstract storage location paired with an associated symbolic name, which contains some known or unknown quantity of information referred to as a value.
In simpler terms, a variable is a named container for a particular set of bits or type of data (like integer, float, string etc...).
.PP
A variable can eventually be associated with or identified by a memory address.
The variable name is the usual way to reference the stored value, in addition to referring to the variable itself, depending on the context.
This separation of name and content allows the name to be used independently of the exact information it represents.
.PP
The identifier in computer source code can be bound to a value during run time, and the value of the variable may thus change during the course of program execution.
.TS
tab(;);
l l.
\fBVariables\fR;\fBDescription\fR
_
\fBPERSON_AGE\fR(3);T{
Person age handle.
T}
\fBFooBarDefaultValue\fR(3);T{
This variable refers to a pointer to a structure.
T}
\fBscratch_buffer\fR(3);T{
This variable has an array portion associated with it.
T}
.TE