.TH "MY PROJECT" "3"
.SH NAME
lists.h \- lorem Ipsum
.SH SYNOPSIS
.nf
.B #include <lists.h>
.fi
.SH DESCRIPTION
Recognition of the inherent dignity and of the equal and inalienable rights of all members of the human family.
The foundation of
.PP
.RS
.IP 1. 3
Freedom
.IP 2. 3
Justice
.IP 3. 3
Peace in the world
.RS
.IP 1. 3
Disregard and contempt
.IP 2. 3
for human rights have resulted in barbarous acts which have outraged the conscience of mankind.
.RE
.IP 4. 3
The advent of a world
.IP 5. 3
In which human beings
.IP 6. 3
Shall enjoy freedom from
.IP 7. 3
fear and want has
.IP 8. 3
been proclaimed as
.IP 9. 3
the highest aspiration
.IP 10. 4
of the common people.
.IP 11. 4
Whereas it is essential, if man is not to be compelled to have recourse, as a last resort, to rebellion against tyranny and oppression, that human rights should be protected by the rule of law.
.RE
.PP
Now lets test nested lists:
.PP
A list of events:
.RS
.IP 1. 3
mouse events
.RS
.IP 1. 3
mouse move event
.IP 2. 3
mouse click event
.IP 3. 3
mouse double click event
.RE
.IP 2. 3
keyboard events
.RS
.IP 1. 3
key down event
.IP 2. 3
key up event
.RE
.RE
.PP
More text here.
.PP
Text before the list
.RS
.IP 1. 3
list item 1
.RS
.IP 1. 3
sub item 1
.RS
.IP 1. 3
sub sub item 1
.IP 2. 3
sub sub item 2
.RE
The dot above ends the sub sub item list.More text for the first sub item
.RE
The dot above ends the first sub item.More text for the first list item
.RS
.IP 1. 3
sub item 1 (start a new list)
.IP 2. 3
sub item 2
.RE
.IP 2. 3
list item 2
.RE
More text in the same paragraph.
.PP
More text in a new paragraph.