.TH "MY PROJECT" "3"
.SH NAME
copy_me \- copies a buffer
.SH SYNOPSIS
.nf
.B #include <functions-params.h>
.PP
.BI "const char *copy_me(char " dest "[64], int ***" fds "[2]);"
.fi
.SH DESCRIPTION
Copies content from file descriptors \f[I]fd\f[R] to \f[I]dest\f[R].
.SH RETURN VALUE
String content of \f[I]buffer\f[R].