.TH "MY PROJECT" "3"
.SH NAME
functions-params.h \- testing function parameters
.SH SYNOPSIS
.nf
.B #include <functions-params.h>
.fi
.SH DESCRIPTION
Lets see if function parameters can be referenced.
.TS
tab(;);
l l.
\fBFunctions\fR;\fBDescription\fR
_
\fBclose_me\fR(3);T{
Closes a file descriptor.
T}
.TE