.TH "MY PROJECT" "3"
.SH NAME
barracuda_t \- this is an named enumeration with an alias
.SH SYNOPSIS
.nf
.B #include <typedef.h>
.PP
.BI "typedef enum Barracuda barracuda_t;"
.fi
.SH DESCRIPTION
This enumeration has a name and an alias associated with it.
You can refer to it by \f[B]Barracuda\f[R](3) or by the \f[B]barracuda_t\f[R](3) alias.
.SH SEE ALSO
.BR Barracuda (3)