.TH "MY PROJECT" "3"
.SH NAME
Barracuda \- this is an named enumeration with an alias
.SH SYNOPSIS
.nf
.B #include <typedef.h>
.PP
enum Barracuda {
    FISH,
    SHARK,
    OCTOPUS,
};
.fi
.SH DESCRIPTION
This enumeration has a name and an alias associated with it.
You can refer to it by \f[B]Barracuda\f[R](3) or by the \f[B]barracuda_t\f[R](3) alias.
.SH CONSTANTS
.TP
.BR FISH
.TP
.BR SHARK
.TP
.BR OCTOPUS
.SH SEE ALSO
.BR barracuda_t (3)