.TH "MY PROJECT" "3"
.SH NAME
barracuda_t \- this is an named enumeration with an alias
.SH SYNOPSIS
.nf
.B #include <alias.h>
.PP
.B "enum barracuda_t {"
.B "    FISH,"
.B "    SHARK,"
.B "    OCTOPUS,"
.B "};"
.fi
.SH DESCRIPTION
This enumeration has a name and an alias associated with it.
You can refer to it by #Barracuda or by the \f[B]barracuda_t\f[R](3) alias.
.SH CONSTANTS
.TP
.BR FISH
.TP
.BR SHARK
.TP
.BR OCTOPUS