.TH "MY PROJECT" "3"
.SH NAME
frob_t \- this is an unnamed enumeration
.SH SYNOPSIS
.nf
.B #include <typedef.h>
.PP
enum frob_t {
    FOO,
    BAR,
    BAZ,
};
.fi
.SH DESCRIPTION
It is anonymous but you may refer to it by the \f[B]frob_t\f[R](3) typedef alias.
.SH CONSTANTS
.TP
.BR FOO
.TP
.BR BAR
.TP
.BR BAZ