.TH "MY PROJECT" "3"
.SH NAME
ptrstring_t \- structure pointer with typedef
.SH SYNOPSIS
.nf
.B #include <typedef.h>
.PP
.BI "typedef struct string_t *ptrstring_t;"
.fi
.SH DESCRIPTION
A pointer to this structure declared with a typedef.
.PP
This is typically bad practice in real API's as it hides the pointer.
Better to use \f[B]string_t\f[R](3) instead or better yet use \f[B]String\f[R](3) directly.
.SH SEE ALSO
.BR string_t (3),
.BR String (3)