.TH "MY PROJECT" "3"
.SH NAME
string_t
.SH SYNOPSIS
.nf
.B #include <None>
.PP
.B struct string_t {
.RS
.B int length;
.B const char *buffer;
.B int length;
.B const char *buffer;
.RE
.B };
.fi
.SH DESCRIPTION
Structure pointer with typedef.
.PP
This structure is declared with a typedef.
It's preferred to use this directly over the #ptrstring_t typedef because the latter hides the pointer.
.PP
A pointer to this structure declared with a typedef.
.PP
This is typically bad practice in real API's as it hides the pointer.
Better to use \f[B]string_t\f[R](3) instead or better yet use #String directly.