.TH "MY PROJECT" "3"
.SH NAME
variant_t \- union with typedef
.SH SYNOPSIS
.nf
.B #include <typedef.h>
.PP
.BI "typedef union Variant variant_t;"
.fi
.SH DESCRIPTION
This union is declared with a typedef.
It's preferred to use this directly over the \f[B]ptrvariant_t\f[R](3) typedef because the latter hides the pointer.
.SH SEE ALSO
.BR ptrvariant_t (3)