.TH "MY PROJECT" "3"
.SH NAME
bar \- bar
.\" --------------------------------------------------------------------------
.SH SYNOPSIS
.nf
.B #include <referenced.h>
.PP
.BI "void bar(void);"
.fi
.\" --------------------------------------------------------------------------
.SH DESCRIPTION
Let's reference multiple functions use Doxygen commands.
.\" --------------------------------------------------------------------------
.SH SEE ALSO
.BR foo (3),
.BR baz (3)
