.TH "MY PROJECT" "3"
.SH NAME
baz \- baz
.\" --------------------------------------------------------------------------
.SH SYNOPSIS
.nf
.B #include <referenced.h>
.PP
.BI "void baz(void);"
.fi
.\" --------------------------------------------------------------------------
.SH DESCRIPTION
Let's reference another function.
.\" --------------------------------------------------------------------------
.SH SEE ALSO
.BR bar (3)
