.TH "MY PROJECT" "3"
.SH NAME
referenced.h \- referenced functions
.\" --------------------------------------------------------------------------
.SH SYNOPSIS
.nf
.B #include <referenced.h>
.fi
.\" --------------------------------------------------------------------------
.SH DESCRIPTION
Let's reference other functions.
Like \f[B]foo\f[R](3) and \f[B]bar\f[R](3).
.PP
.\" -------------------------------------
.SS Functions
.TP
.BR foo (3)
Foo.
.TP
.BR bar (3)
Bar.
.TP
.BR baz (3)
Baz.
.\" --------------------------------------------------------------------------
.SH SEE ALSO
.BR foo (3),
.BR bar (3),
.BR baz (3)
