.TH "MY PROJECT" "3"
.SH NAME
referenced.h \- referenced functions
.SH SYNOPSIS
.nf
.B #include <referenced.h>
.fi
.SH DESCRIPTION
Let's reference other functions.
Like \f[B]foo\f[R](3) and \f[B]bar\f[R](3).
.TS
tab(;);
l l.
\fBFunctions\fR;\fBDescription\fR
_
\fBfoo\fR(3);T{
Foo.
T}
\fBbar\fR(3);T{
Bar.
T}
\fBbaz\fR(3);T{
Baz.
T}
.TE
.SH SEE ALSO
.BR foo (3),
.BR bar (3),
.BR baz (3)