.TH "UNICORN" "3"
.SH NAME
unisize \- code unit count
.SH LIBRARY
Embeddable Unicode Algorithms (libunicorn, -lunicorn)
.SH SYNOPSIS
.nf
.B #include <unicorn.h>
.PP
.BI "typedef long unisize;"
.fi
.SH DESCRIPTION
An integer type whose storage size represents the maximum potential length (in code units) of encoded text.