.TH "UNICORN" "3"
.SH NAME
unistrength \- number of levels to be considered in comparison
.SH LIBRARY
Embeddable Unicode Algorithms (libunicorn, -lunicorn)
.SH SYNOPSIS
.nf
.B #include <unicorn.h>
.PP
.B "enum unistrength {"
.B "    UNI_PRIMARY,"
.B "    UNI_SECONDARY,"
.B "    UNI_TERTIARY,"
.B "    UNI_QUATERNARY,"
.B "};"
.fi
.SH DESCRIPTION
The Unicode collation algorithm is a multilevel comparison algorithm.
The number of levels that are considered in comparison is known as the collation strength.
This enumeration defines constants describing each level.
.SH CONSTANTS
.TP
.BR UNI_PRIMARY
Represents differences in the base letter or symbol.
.TP
.BR UNI_SECONDARY
Represents differences in accents.
.TP
.BR UNI_TERTIARY
Represents differences in case or variants of symbols.
.TP
.BR UNI_QUATERNARY
Represents differences in punctuation.