.TH "UNICORN" "3"
.SH NAME
unistat \- status code
.SH LIBRARY
Embeddable Unicode Algorithms (libunicorn, -lunicorn)
.SH SYNOPSIS
.nf
.B #include <unicorn.h>
.PP
.B enum unistat {
.RS
.B UNI_OK,
.B UNI_DONE,
.B UNI_NO_MEMORY,
.B UNI_NO_SPACE,
.B UNI_BAD_ENCODING,
.B UNI_BAD_OPERATION,
.B UNI_FEATURE_DISABLED,
.B UNI_MALFUNCTION,
.RE
.B };
.fi
.SH DESCRIPTION
Most functions in the Unicorn library return an element of this enumeration.
Of the elements, only \f[B]UNI_OK\f[R] and \f[B]UNI_DONE\f[R] represent a success status whereas the others represent failures.
.SH CONSTANTS
.TP
.BR UNI_OK
Represents the successful execution of an operation.
.TP
.BR UNI_DONE
Represents the successful completion of an operation.
An example of function that returns this status code is \f[B]uni_nextbrk\f[R](3) which returns it when the end of the input string has been reached.
.TP
.BR UNI_NO_MEMORY
Functions that potentially allocate memory will have this element listed as one of their potential return values.
Functions that omit this element as a potential return code do not perform dynamic memory allocation.
.TP
.BR UNI_NO_SPACE
This status code indicates that a larger buffer must be given.
.TP
.BR UNI_BAD_ENCODING
Examples of malformed character sequences would be overlong sequences in UTF-8 or unpaired surrogate characters in UTF-16.
.TP
.BR UNI_BAD_OPERATION
This failure code is returned by functions when they are called with invalid arguments.
For instance a function might return this code when given a null pointer when a non-null pointer was expected.
.TP
.BR UNI_FEATURE_DISABLED
Unicorn allows consumers to customize which Unicode features it’s built with.
This is useful for reducing the overall size of the library for memory constrained environments.
If a user attempts to use a feature (e.g.
call a function) that is disabled then this status code is returned.
.TP
.BR UNI_MALFUNCTION
In a working version of Unicorn, an application will never see this status code.
If an application does encounter this code, it means there is a bug in Unicorn.
.SH SEE ALSO
.BR uni_nextbrk (3)