.TH "UNICORN" "3"
.SH NAME
uniweighting \- collation weighting algorithm
.SH LIBRARY
Embeddable Unicode Algorithms (libunicorn, -lunicorn)
.SH SYNOPSIS
.nf
.B #include <unicorn.h>
.PP
.B enum uniweighting {
.RS
.B UNI_NON_IGNORABLE,
.B UNI_SHIFTED,
.RE
.B };
.fi
.SH DESCRIPTION
This enumeration defines constants representing the possible options for variable weighted characters.
.PP
The Unicode Collation Algorithm defines the collation for some characters as variable.
This typically includes punctuation characters and symbols.
Based on the variable-weighting setting, these characters can be interpreted as having a \f[B]UNI_QUATERNARY\f[R].
.SH CONSTANTS
.TP
.BR UNI_NON_IGNORABLE
The words with hyphen-minus or hyphen are grouped together, but before all letters in the third position.
This is because they are not ignorable, and have primary values that differ from the letters.
The symbols ☠ and ♡ have primary differences.
.TP
.BR UNI_SHIFTED
The hyphen-minus and hyphen are grouped together, and their differences are less significant than the casing differences in the letter “l”.
This grouping results from the fact that they are ignorable, but their fourth level differences are according to the original primary order, which is more intuitive than Unicode order.
The symbols ☠ and ♡ are ignored on levels 1-3.
.SH SEE ALSO
.BR unistrength (3)