.TH "MY PROJECT" "3"
.SH NAME
inline-code.h \- inline code styling
.SH SYNOPSIS
.nf
.B #include <inline-code.h>
.fi
.SH DESCRIPTION
Recognition of the \f[V]inherent dignity\f[R] and of the equal and inalienable rights of all members of the human family.
The foundation of freedom, \f[V]justice\f[R] and peace in the world.