.TH "MY PROJECT" "3"
.SH NAME
Frob
.SH SYNOPSIS
.nf
.B #include <structs.h>
.PP
.B struct Frob {
.RS
.B const void *nop;
.B const void *nop;
.RE
.B };
.fi
.SH DESCRIPTION
This structure has one field.
It doesn't do much otherwise.
It is generally recommended to prefer the \f[B]Foo\f[R](3) structure as it's more modern.
.SH FIELDS
.TP
.BR nop
This field has no use.
It can be treated as scratch storage.
.TP
.BR nop
This field has no use.
It can be treated as scratch storage.
.SH SEE ALSO
.BR Foo (3)