.TH "MY PROJECT" "3"
.SH NAME
pi \- retrieve the mathematical constant of the same name
.\" --------------------------------------------------------------------------
.SH SYNOPSIS
.nf
.B #include <simple.h>
.PP
.BI "double pi(void);"
.fi
.\" --------------------------------------------------------------------------
.SH DESCRIPTION
The number π (/paɪ/; spelled out as "pi") is a mathematical constant that is the ratio of a circle's circumference to its diameter, approximately equal to 3.14159.
The number π appears in many formulae across mathematics and physics.
It is an irrational number, meaning that it cannot be expressed exactly as a ratio of two integers
.\" --------------------------------------------------------------------------
.SH RETURN VALUE
The mathematical constant π.
