.TH "AUDITION" "3"
.SH NAME
ASSERT_EQ \- check two integers, floating-point numbers, or pointers to determine if X == Y
.SH LIBRARY
Modern xUnit testing framework for C11 and beyond.
.SH SYNOPSIS
.nf
.B #include <audition.h>
.PP
.BI "#define ASSERT_EQ(" X ", " Y ", " ... ");"
.fi
.SH DESCRIPTION
If X != Y, the test case is aborted.