.TH "AUDITION" "3"
.SH NAME
audit_sleep \- suspends the execution of the current thread until the time-out interval elapses
.SH LIBRARY
Modern xUnit testing framework for C11 and beyond.
.SH SYNOPSIS
.nf
.B #include <audition.h>
.PP
.BI "void audit_sleep(audit_time " duration ");"
.fi
.SH DESCRIPTION
This is useful for introducing artificial delays.
.SH SEE ALSO
.BR audit_time (3)