.TH "AUDITION" "3"
.SH NAME
audit_time \- elapsed time (in milliseconds)
.SH LIBRARY
Modern xUnit testing framework for C11 and beyond.
.SH SYNOPSIS
.nf
.B #include <audition.h>
.PP
.BI "typedef unsigned long long audit_time;"
.fi
.SH DESCRIPTION
This is used by various test utilities for measuring time.