.TH "AUDITION" "3"
.SH NAME
audit_now \- monotonic time in milliseconds
.SH LIBRARY
Modern xUnit testing framework for C11 and beyond.
.SH SYNOPSIS
.nf
.B #include <audition.h>
.PP
.BI "audit_time audit_now(void);"
.fi
.SH DESCRIPTION
This function returns a monotonic time instance measured in milliseconds.
This is intended for benchmarking.
.SH RETURN VALUE
Monotonic time in milliseconds.