.TH "AUDITION" "3"
.SH NAME
EXPECT_EQ_APPROX \- check two floating-point numbers to determine if X ≈ Y with the specified tolerance
.SH LIBRARY
Modern xUnit testing framework for C11 and beyond.
.SH SYNOPSIS
.nf
.B #include <audition.h>
.PP
.BI "#define EXPECT_EQ_APPROX(" X ", " Y ", " T ", " ... ");"
.fi
.SH DESCRIPTION
If X ≉ Y, the test case fails.