.TH "AUDITION" "3"
.SH NAME
StatusCode \- integer representing an application status code
.SH LIBRARY
Modern xUnit testing framework for C11 and beyond.
.SH SYNOPSIS
.nf
.B #include <audition.h>
.PP
.BI "typedef int64_t StatusCode;"
.fi
.SH DESCRIPTION
POSIX requires the exit code to be in the inclusive range 0 to 255.
Windows uses 32-bit unsigned integers as exit codes.