.TH "AUDITION" "3"
.SH NAME
TEST \- entry point for a unit test
.SH LIBRARY
Modern xUnit testing framework for C11 and beyond.
.SH SYNOPSIS
.nf
.B #include <audition.h>
.PP
.BI "#define TEST(" SUITE_NAME ", " TEST_NAME ", " ... ");"
.fi
.SH DESCRIPTION
It should be followed by a pair of opening and closing curly braces with the test statements inserted between them.
.SH SEE ALSO
.BR TestOptions (3)