.TH "AUDITION" "3"
.SH NAME
TEST_ITERATION \- the iteration index of the currently executing loop test case
.SH LIBRARY
Modern xUnit testing framework for C11 and beyond.
.SH SYNOPSIS
.nf
.B #include <audition.h>
.PP
.B int32_t TEST_ITERATION;
.fi
.SH DESCRIPTION
If the currently executing test is not a loop test, then zero is returned.