.TH "AUDITION" "3"
.SH NAME
TestOptions
.SH LIBRARY
Modern xUnit testing framework for C11 and beyond.
.SH SYNOPSIS
.nf
.B #include <audition.h>
.PP
.B struct TestOptions {
.RS
.B int32_t iterations;
.B StatusCode exit_status;
.B int64_t signal;
.B int timeout;
.B bool sandbox;
.B int32_t iterations;
.B StatusCode exit_status;
.B int64_t signal;
.B int timeout;
.B bool sandbox;
.RE
.B };
.fi
.SH DESCRIPTION
This structure defines configuration options applied to the test.