name: Build Status
on: [push, pull_request]
jobs:
  python:
    name: "Python ${{ matrix.python-version }}"
    runs-on: "ubuntu-latest"
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.12"] # Test the oldest and newest supported Python and Doxygen versions.
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        sudo apt-get install doxygen
    - name: Install package
      run: |
        pip install .
    - name: Type checking
      run: |
        mypy --strict manos
        mypy --strict tests
    # The version of Ubuntu supported by GitHub Actions at the time of this writing is version 22.04 LTS.
    # The latest version of Doxygen supported by Ubuntu 22.04 is 1.9.1 which is one patch version behind the
    # minimum version required by Manos. The tests cannot be run on GitHub until they update to a version
    # of Ubuntu that ships the expected Doxygen version (in the interm please run the tests locally).
    # - name: Test
    #   run: |
    #     pytest --cov-report=term-missing --cov-config=pyproject.toml --cov=manos --cov=tests --cov-fail-under=90
